### ISSUE TITLE
Issue with the Fuel Pump System

### ISSUE THREAD

**Issue by OrangeTiger** [yuriknsk/tu154b#37]
When you have the fuel source selector switch set to auto
![fgfs-screen-001](https://cloud.githubusercontent.com/assets/13977319/10011894/9cbc1188-6101-11e5-8801-2204081c0ab0.png)
and there is no fuel in fuel tank no. 4 (ballast tank) the fuel pump system doesn't work. So when tank 1 is getting empty the pumps do not start to drain fuel from tank 2 into tank 1.

This error doesn't occur when you have fuel in the ballast tank (even if its only 1%).
When you switch the fuel source selector switch back to manual he starts to drain fuel from tank 2 into tank 1, as it should be.

**Comment by kroki** [comment]
Thanks for the report!  I didn't know about this bug, but we are aware of few more.  So we decided that fuel subsystem has reached its critical mass and I'm currently in the process of rewriting it.  I expect to finish by the end of this week.

**Comment by OrangeTiger** [comment]
So, I will close this issue, because you are already working on a fix.

**Comment by kroki** [comment]
FYI new fuel subsystem implementation has been merged.
