### ISSUE TITLE
ILS approach issue

### ISSUE THREAD

**Issue by OrangeTiger** [yuriknsk/tu154b#39]
I have noticed a problem with the ILS:

When you are aligned with the runway vertically, but the horizontal component (glideslope indicator) is not in reach yet, and you "arm" the autopilot glideslope the aircraft maintains altitude until the glideslope indicator comes in range. But normally at this time you are below the glidepath so the aircraft pulls up very hard and you have to watch out not to stall. Hopfully you can understand the problem :)

From other aircrafts I know that they maintain altitude until they start to descent on the glidepath.

My first question is, if the Tu-154B can "arm" the autopilot glideslope or if you have to activate it manually, when you start the approach.

**Comment by kroki** [comment]
I understood the question, but we'll need some time to figure things out.

**Comment by kroki** [comment]
@OrangeTiger, what do you mean by "arming" the autopilot glideslope?  Did you press the `ГЛИСС` button?

**Comment by OrangeTiger** [comment]
By "arming" I mean that I pressed the "GLISS" button before the glideslope is in range.

I think a way to fix this problem would be, that when the aircraft is below the glidepath it's holding the altitude instead of climbing.

**Comment by kroki** [comment]
Pressing GLISS is a violation of the procedure, so no bug here.  Do everything as before but do not press the button.  In the plane is in the landing configuration then it will lock on the glideslope automatically, and GLISS button will lit.  Only if for some reason it doesn't lock (wrong flaps, gears up - i.e. non-landing configuration) should you press the button manually, and then you have to do so at the right moment (when you cross the glideslope).

Please confirm that automatic locking works for you and close then this report.

**Comment by soitanen** [comment]
If I remember correctly, in Tu-154 autopilot glideslope mode automatically
engages if you have landing configuration (flaps 45, gear down), localizer
mode and this occurs when passing through glideslope beam. And this is
harcoded to autopilot, you don't need to arm it manually.
But I don't remember what should happen if you press GLISS button before GS
capture.
25 Сен 2015 г. 15:22 пользователь "Christian Nolden" <
notifications@github.com> написал:

**Comment by kroki** [comment]
GLISS button is essentially a command "follow glideslope _now_", so the observed behaviour is correct.

**Comment by OrangeTiger** [comment]
Thanks for these answeres.

I always crossed the glidepath with flaps 28 and gears up and extended both right after establishing the glideslope. So I'm going to change the procedure so that I have full flaps and gears down before crossing the glidepath and will see if "GLISS" will auto capture.

I cannot try this right now, but I will do it later today and close the issue.

**Comment by kroki** [comment]
I'm not familiar with current autopilot code, but a year ago we definitely supported late gear extension.  So maybe all you need is 45 flaps.

**Comment by kroki** [comment]
I just checked with Flight Manual, required conditions for automatic engagement of GLISS are:
- lamp button `ЗАХОД` is enabled
- flaps are 45 degrees

There's no requirement regarding gears.

**Comment by OrangeTiger** [comment]
which flight manual did you use?

**Comment by kroki** [comment]
We have a shortened variant in Russian from Project Tupolev, `Docs/PT_Docs/PT154b-rle.pdf` in source tree (p.111, section (6)).

**Comment by OrangeTiger** [comment]
Autocapture works when you have flaps to 45, so thanks :)
